module.exports = {
    units: { bought: Number, left: Number },
    period: Number,
    installation: Boolean,
    date: Date,
    accessories: {
        alarmJLPD: { bought: Number, left: Number },
        alarmWTQR3: { bought: Number, left: Number },
        alarmWTRS2: { bought: Number, left: Number },
        alarmWTRSF1865: { bought: Number, left: Number },
        alarmWTRZ869F1: { bought: Number, left: Number },
        digitalLock: { bought: Number, left: Number },
        dongleRFDGLP2F1: { bought: Number, left: Number },
        doorContactDC15SLF1869: { bought: Number, left: Number },
        doorContactDC23869F1: { bought: Number, left: Number },
        doorContactSDC1: { bought: Number, left: Number },
        drawstringPCU3F1865: { bought: Number, left: Number },
        heatDetectorHD9869F1: { bought: Number, left: Number },
        ioEnhetUT15869F1: { bought: Number, left: Number },
        lockForMedicineCabnet: { bought: Number, left: Number },
        medicineCabnetWithLock: { bought: Number, left: Number },
        meshSystemTPLinkM9: { bought: Number, left: Number },
        motionSensorIR29SL869F1: { bought: Number, left: Number },
        nfcReaders: { bought: Number, left: Number },
        panikknappBP23F1869: { bought: Number, left: Number },
        router240: { bought: Number, left: Number },
        router950: { bought: Number, left: Number },
        smokeDetectorSD8EL869F1: { bought: Number, left: Number },
        telenorSIMCard3GB: { bought: Number, left: Number },
        telenorSIMCard600GB: { bought: Number, left: Number },
        wallBracket240: { bought: Number, left: Number },
        wallBracketTPLinkM9: { bought: Number, left: Number },
        waterDetectorWLS15869MF1: { bought: Number, left: Number },
    },
};
